### ISSUE TITLE
Upload generated docs to docs.ledgersmb.org for each release.

### ISSUE THREAD

**Issue by hasorli** [ledgersmb/ledgersmb-release-tools#2]
Extend the release process by uploading generated docs to docs.ledgersmb.org for each release.
but that would be more useful if the dot output would be transformed into SVG

The database docs are here: https://github.com/ledgersmb/LedgerSMB/tree/1.5/doc/database
Make it part of the release process to update them.

source: ehuelsmann : from #ledgersmb:matrix.org  2017.02.11

Add generated pod documentation. Generate with 
$ make pod

**Comment by ehuelsmann** [comment]
Implemented in cb236a5688fd254c8f7e4e8c09f11211dc7fc71f.
